Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "copyright", "credits" or "license()" for more information.
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 1, in <module>
    from numpy import *     # Importē skaitlisko metožu bibliotēkas funkcijas
ModuleNotFoundError: No module named 'numpy'
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 1, in <module>
    from numpy import *     # Importē skaitlisko metožu bibliotēkas funkcijas
ModuleNotFoundError: No module named 'numpy'
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 2, in <module>
    x = linspace(0, 7, 70)  # Trešais arguments ir ģenerējamo elementu skaits
NameError: name 'linspace' is not defined
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 1, in <module>
    from numpy import *     # Importē skaitlisko metožu bibliotēkas funkcijas
ModuleNotFoundError: No module named 'numpy'
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 1, in <module>
    from numpy import *     # Importē skaitlisko metožu bibliotēkas funkcijas
ModuleNotFoundError: No module named 'numpy'
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 1, in <module>
    from numpy import *     # Importē skaitlisko metožu bibliotēkas funkcijas
ModuleNotFoundError: No module named 'numpy'
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 1, in <module>
    from NumPy import *     # Importē skaitlisko metožu bibliotēkas funkcijas
ModuleNotFoundError: No module named 'NumPy'
>>> import sys
>>> sys.path.append("/usr/local/anaconda3/lib/python3.6/site-packages/")
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 1, in <module>
    from numpy import *     # Importē skaitlisko metožu bibliotēkas funkcijas
ModuleNotFoundError: No module named 'numpy'
>>> import numpy
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
>>> sys.path.append("/usr/local/anaconda3/lib/python3.6/site-packages")
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    sys.path.append("/usr/local/anaconda3/lib/python3.6/site-packages")
NameError: name 'sys' is not defined
>>> import sys
>>> sys.path.append("/usr/local/anaconda3/lib/python3.6/site-packages")
>>> import numpy
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================

Warning (from warnings module):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py", line 281
    'Matplotlib is building the font cache using fc-list. '
UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
10
	
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================

===================== RESTART: /home/user/RTR105/1B1.py =====================

===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 

===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B2.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B2.py", line 8, in <module>
    y2 = y - x^3/1*2*3*4*5
TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
>>> 
===================== RESTART: /home/user/RTR105/1B2.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B2.py", line 8, in <module>
    y2 = sin(x - x^3/1*2*3*4*5)
TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
>>> 
===================== RESTART: /home/user/RTR105/1B2.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B2.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B2.py", line 21, in <module>
    y3 = y2 + x*x*x*x*X/(1*2*3*4*5)
NameError: name 'X' is not defined
>>> 
===================== RESTART: /home/user/RTR105/1B2.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B2.py", line 24, in <module>
    plt,plot(x, y4, color = "#BFFF00")
NameError: name 'plot' is not defined
>>> 
===================== RESTART: /home/user/RTR105/1B2.py =====================

===================== RESTART: /home/user/RTR105/1B2.py =====================

===================== RESTART: /home/user/RTR105/1B2.py =====================

===================== RESTART: /home/user/RTR105/1B2.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B2.py =====================
>>> 
